### ISSUE TITLE
Shortcut clash

### ISSUE THREAD

**Issue by sanderboom** [hernejj/workspace-grid-cinnamon-applet#7]
Thanks for the great applet.

One issue though: to enable the keyboard shortcuts for move up/down, I have to set the Toggle Scale to Ctrl-Alt-Down and Toggle Expo to Ctrl-Alt-Up. This means I can't use Scale and Toggle anymore.

Can you supply separate shortcut 'slots' for your applet?

Thanks!

**Comment by hernejj** [comment]
Perhaps. All my applet does, as far as keyboard shortcuts, is to de-register Cinnamon's hijacking of the normal desktop-up and desktop-down keyboard shortcuts.  They stole these, and my applet takes them back for their rightful purpose.  Ideally, I would like to see Cinnamon simply create NEW key bindings for expo and whatever the other one did (can't remember at the moment) so that way the user could have a choice. This would be the best approach I think.

**Comment by deepfire** [comment]
If you could provide a pointer on where I could effectively chime in on the matter, so they would have user feedback -- I would.

**Comment by hernejj** [comment]
This will be fixed in v0.5. Which should be posted some time in the next 8 hours :). Now that the applet has been converted to the Cinnamon Settings api, I can easily provide a setting to simply avoid registering the offending key bindings.
