### ISSUE TITLE
Show all rows as it is in gnome 2.

### ISSUE THREAD

**Issue by horada** [hernejj/workspace-grid-cinnamon-applet#9]
Hi,
and second question/tip for enhancement - would it be possible to show all workspaces in all rows in grid as it was in gnome 2? (it was easier for me to see where I'm... and "which way" to the next workspace...)
It would be also nice, to see "rectangles" representing open windows on each workspace... but it's probably too complicated...

**Comment by hernejj** [comment]
Showing the entire grid in the panel, using the default panel size, is not really possible for more than 1 or maybe 2 rows. The boxes become way too small and thus, hard to see. perhaps instead of using "large square boxes" to represent a desktop, I could use smaller un-numbered boxes and simply draw out the entire grid. Just like the current method, up to 6x6 would probably be an upper limit. Would this suffice for your needs? Maybe the applet could do both. The user selects the desired behavior via an option.

As for window previews, are they useful if we only have a single row visible on the panel at any given time? If there is more than one row, then window previews are certainly not sensible as they would be too small. A larger grid preview displayed in the center of the screen while switching could potentialy work. What do you think?

**Comment by horada** [comment]
For me, it would be good just the grid without any number - with highlighted active workspace.

The window preview would be just "an icing on the cake"... and you are right that that even in gnome2 it probably doesn't work for more than two rows.... Just new idea - maybe only distinguish empty workspaces and workspaces with some window... but I'm not sure if it will be usable...

**Comment by hernejj** [comment]
That is an awesome idea :+1:  I would love to be able to determine if a workspace is empty with a single glance.  I will consider these ideas. Thanks!

**Comment by hernejj** [comment]
I've added a new visual style to the applet to show you all rows/columns in a grid. Please let me know if this satisfies your request. The updated applet is v0.6 and can be found via the Cinnamon applets website or you can update it from the "Add Applets" window.

I'm leaving this bug open as I have not yet addressed indicating the existence or lack of windows within desktops.

**Comment by horada** [comment]
That's exactly what I meant, great!  Thanks...

**Comment by jonorthwash** [comment]
This feature is working great, thanks!  I was wondering if a couple subfeatures could be added to it.  If you'd like me to file these as separate issues, just let me know.

The window preview idea would be nice (so that one could see if a workspace is empty at a glance, as mentioned), and is one of the things I was going to ask for.

The other feature request is to have the workspace icons scaled to the dimensions of the screen, as opposed to just being fixed [4:3?] rectangles.

**Comment by hernejj** [comment]
Feel free to open another issue. We can discuss it there.
